Repository De-cal/6-Snack-BE, pull requests merged in 2025-08, with the labels that each got.

#94 feat: 찜 목록 조회 응답 수정 [이태빈]
  src/repositories/favorite.repository.ts
  src/services/favorite.service.ts
Labels: Feature, Refactor

#98 refactor: order 쿼리스트링 수정(offset -> page) [이태빈]
  http/order.http
  src/controllers/order.controller.ts
  src/dtos/order.dto.ts
  src/repositories/order.repository.ts
  src/services/order.service.ts
  src/types/order.types.ts
Labels: Route, Refactor

#100 refactor: favorite offset기반 페이지네이션에서 cursor기반 페이지네이션으로 변경 [이태빈]
  http/favorite.http
  src/controllers/favorite.controller.ts
  src/dtos/favorite.dto.ts
  src/repositories/favorite.repository.ts
  src/services/favorite.service.ts
  src/types/favorite.types.ts
Labels: Refactor

#96 feat: 좋아요 추가 [김우주]
  http/favorite.http
  http/order.http
  http/product.http
  prisma/mocks/like.mock.ts
  src/controllers/product.controller.ts
  src/middlewares/jwtAuth.middleware.ts
  src/repositories/product.repository.ts
  src/routes/product.route.ts
  src/services/product.service.ts
  src/types/product.types.ts
Labels: Feature

#102 refactor: Swagger 문서용 주석 추가, favorite 페이지네이션 변경(cursor) [이태빈]
  src/controllers/budget.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/order.controller.ts
  src/dtos/favorite.dto.ts
  src/routes/admin.route.ts
  src/routes/adminBudget.route.ts
  src/routes/superAdmin.route.ts
  src/routes/superAdminBudget.route.ts
  src/services/favorite.service.ts
  src/types/favorite.types.ts
Labels: Route, Refactor

#101 test: 테스트 코드 작성, Swagger 코드 작성 [김홍섭]
  src/__tests__/sum.test.ts
  src/controllers/auth.controller.test.ts
  src/controllers/auth.controller.ts
  src/controllers/invite.controller.test.ts
  src/controllers/invite.controller.ts
  src/controllers/user.controller.test.ts
  src/controllers/user.controller.ts
  src/services/auth.service.test.ts
  src/services/invite.service.test.ts
  src/services/user.service.test.ts
Labels: Test

#104 chore: 스키마 수정(Payment 테이블 추가, orderId uuid로 변경) [이태빈]
  package-lock.json
  package.json
  prisma/migrations/20250803150425_add_payment_table_and_change_order_id_type_uuid/migration.sql
  prisma/migrations/20250803194833_add_field_in_payment/migration.sql
  prisma/schema.prisma
  src/controllers/order.controller.ts
  src/repositories/order.repository.ts
  src/services/order.service.ts
Labels: Feature, Chore

#106 test:테스트 코드 작성 및 cartAPI swagger 작성 [조성빈]
  src/controllers/cart.controller.test.ts
  src/controllers/cart.controller.ts
  src/services/cart.service.test.ts
Labels: Test

#108 feat: 보안을 위한 helmet 미들웨어 추가 및 로깅을 위한 morgan 미들웨어 추가
  package-lock.json
  package.json
  src/app.ts
Labels: Chore

#109 feat: EC2 자동 배포를 위한 GitHub Actions 워크플로우 세팅
  .github/workflows/deploy.yml
Labels: Chore

#110 feat: EC2 자동 배포를 위한 GitHub Actions 워크플로우 세팅 deploy.yml 파일 개선(환경변수, 테스트코드 실행 추가)
  .github/workflows/deploy.yml
Labels: Chore

#105 feat: 토스페이먼츠 결제 모듈 API 연동 및 Payment 로직 추가 [이태빈]
  http/tossPayments.http
  src/app.ts
  src/controllers/payment.controller.ts
  src/repositories/payment.repository.ts
  src/routes/index.route.ts
  src/routes/payment.route.ts
  src/services/payment.service.ts
Labels: Feature, Route

#111 fix: 시딩 시 존재하지 않는 시퀀스 참조로 인한 에러 해결 [김홍섭]
  prisma/seed.ts
Labels: Bug

#112 feat: 최고관리자 관련 API Test 코드 작성 & Swagger 주석 추가 [이지수B]
  src/controllers/company.controller.test.ts
  src/controllers/company.controller.ts
  src/controllers/user.controller.test.ts
  src/controllers/user.controller.ts
  src/services/company.service.test.ts
  src/services/user.service.test.ts
Labels: Chore, Test

#115 refactor: receipt mock 데이터 변경, 시드파일 업데이트 [이지수B]
  http/auth.http
  http/user/user.company.http
  prisma/mocks/receipt.mock.ts
  prisma/seed.ts
Labels: Bug, Refactor

#116 fix: 스웨거 오류 잡음 [김우주]
  http/order.http
  src/controllers/product.controller.ts
Labels: Bug

#117 QA: route 비즈니스 로직 controller/service/repository로 분리 [김홍섭]
  src/controllers/invite.controller.ts
  src/dtos/invite.dto.ts
  src/repositories/invite.repository.ts
  src/routes/invite.route.ts
  src/services/invite.service.ts
Labels: Refactor, QA

#118 fix: test code 타입에러 수정 [이지수B]
  src/controllers/company.controller.test.ts
  src/services/company.service.test.ts
Labels: Bug

#120 feat: 센트리 적용, swagger 문서 수정 [이태빈]
  http/payment.http
  package-lock.json
  package.json
  src/app.ts
  src/config/swagger.ts
  src/controllers/payment.controller.ts
  src/instrument.ts
Labels: Feature

#126 refactor: 테스트 코드 삭제 [이태빈]
  src/routes/payment.route.ts
Labels: Refactor

#127 feat: 결제 모듈 오류 해결 [이태빈]
  src/controllers/payment.controller.ts
Labels: Refactor

#130 refactor: 로그인 쿠키 도메인 설정 [이태빈]
  src/controllers/auth.controller.ts
Labels: Bug

#132 test: CI/CD 테스트 [이태빈]
  http/payment.http
Labels: Feature

#135 feat: 유닛 테스트 코드 작성 [이태빈]
  .github/workflows/deploy.yml
  prisma/migrations/20250811003025_add_new_order_model_field_and_order_status_enum/migration.sql
  prisma/schema.prisma
  src/controllers/budget.controller.test.ts
  src/controllers/favorite.controller.test.ts
  src/controllers/favorite.controller.ts
  src/controllers/order.controller.test.ts
  src/controllers/orderRequest.controller.ts
  src/controllers/payment.controller.test.ts
  src/cron/autoCreateMonthlyBudget.ts
  src/cron/createMonthlyBudget.test.ts
  src/cron/createMonthlyBudget.ts
  src/middlewares/validateBudgetBody.middleware.test.ts
  src/middlewares/validateBudgetBody.middleware.ts
  src/middlewares/validateGetOrderQuery.middleware.test.ts
  src/middlewares/validateUpdateStatusOrderBody.middleware.test.ts
  src/repositories/orderRequest.repository.ts
  src/routes/orderRequest.route.ts
  src/services/budget.service.test.ts
  src/services/favorite.service.test.ts
  src/services/order.service.test.ts
  src/services/orderRequest.service.ts
  src/services/payment.service.test.ts
  src/types/orderRequest.types.ts
Labels: Test

#136 refactor: s3 관련 함수 개선, 목데이터 업데이트 [이지수B]
  prisma/mocks/monthly-budget.mock.ts
  prisma/mocks/order.mock.ts
  prisma/mocks/product.mock.ts
  prisma/seed.ts
  src/controllers/product.controller.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  src/utils/s3.ts
Labels: Chore, Refactor, QA

#138 feat: 회원탈퇴된 사용자 로그인 차단 로직 추가 (auth.service) [김홍섭]
  src/services/auth.service.ts
Labels: Feature

#140 chore: supertest 설정 [이태빈]
  package-lock.json
  package.json
Labels: Chore

#144 rafactor: 스웨거 최종 수정 [이태빈]
  src/controllers/favorite.controller.ts
  src/controllers/order.controller.ts
  src/routes/adminOrder.route.ts
Labels: Route, Refactor

#143 feat: 결제 모듈 부족한 점 추가 [이태빈]
  http/order.http
  src/controllers/order.controller.ts
  src/controllers/payment.controller.ts
  src/dtos/order.dto.ts
  src/repositories/order.repository.ts
  src/routes/payment.route.ts
  src/services/order.service.ts
  src/types/order.types.ts
Labels: Feature

#146 chore: yml 테스트 코드 실행부분 임시 주석처리 [이지수B]
  .github/workflows/deploy.yml
Labels: Chore

#149 feat: invite, my API 라우트에 Redis 캐시미들웨어 적용; 캐싱미들웨어를 Token검사미들웨어 뒤쪽으로 이동 [김홍섭]
  src/routes/invite.route.ts
  src/routes/my.route.ts
Labels: Feature

#150 product, superAdmin 라우트에 redis 추가 [조성빈]
  src/routes/product.route.ts
  src/routes/superAdmin.route.ts
Labels: Route, Refactor

#153 feat: Redis 적용 [이태빈]
  src/routes/admin.route.ts
  src/routes/adminOrder.route.ts
  src/routes/user.route.ts
Labels: Feature

#151 refactor: order,payment 라우트 수정 [김우주]
  src/routes/order.route.ts
  src/routes/payment.route.ts
Labels: Feature, Route

#155 refactor: 스웨거 태그 수정 [이지수B]
  src/controllers/company.controller.ts
  src/controllers/user.controller.ts
Labels: Chore

#156 refactor: 스웨거 변경 [김우주]
  src/config/swagger.ts
  src/controllers/auth.controller.ts
  src/controllers/budget.controller.ts
  src/controllers/cart.controller.ts
  src/controllers/company.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/invite.controller.ts
  src/controllers/order.controller.ts
  src/controllers/product.controller.ts
  src/controllers/user.controller.ts
Labels: Refactor

#161 feat: 레디스 최종 수정 [이태빈]
  src/middlewares/cacheMiddleware.ts
  src/routes/admin.route.ts
  src/routes/adminOrder.route.ts
  src/routes/cart.route.ts
  src/routes/favorite.route.ts
  src/routes/invite.route.ts
  src/routes/my.route.ts
  src/routes/order.route.ts
  src/routes/payment.route.ts
  src/routes/product.route.ts
  src/routes/superAdmin.route.ts
  src/routes/user.route.ts
Labels: Route, Refactor

#162 fix: CI/CD 디버깅 [이태빈]
  .github/workflows/deploy.yml
  src/integration-test/favorite.integration.test.ts
  src/routes/superAdmin.route.ts
Labels: Bug

#165 feat: cache 수정 [이태빈]
  .github/workflows/deploy.yml
  src/routes/auth.route.ts
Labels: Feature

#168 test: 통합 테스트 코드 작성 [김우주]
  .github/workflows/deploy.md
  src/integration-test/product.integration.test.ts
  src/repositories/product.repository.ts
Labels: Test

#169 test: cart 통합테스트 코드 추가 [조성빈]
  src/integration-test/cart.integration.test.ts
Labels: Test

#176 fix: 페이먼트 테스트 코드 수정[김우주]
  src/controllers/payment.controller.test.ts
Labels: Test

#174 test: auth, budgets 테스트코드 개선 및 PASS 확인 [김홍섭]
  src/controllers/auth.controller.test.ts
  src/integration-test/budget.integration.test.ts
Labels: Test

#177 Test/order request
  src/controllers/auth.controller.test.ts
  src/integration-test/budget.integration.test.ts
  src/services/order.service.test.ts
Labels: Test

#183 chore: integration 오류나는 부분 disabled처리 [이지수B]
  src/integration-test/company.integration.test.ts.disabled
  src/integration-test/order.integration.test.ts.disabled
  src/integration-test/user.integration.test.ts.disabled
Labels: Chore

#184 Fix/cicd-hotfix
  .github/workflows/deploy.yml
  src/integration-test/company.integration.test.ts
  src/integration-test/order.integration.test.ts
  src/integration-test/user.integration.test.ts
Labels: Bug

#185 Fix/cicd-hotfix
  src/integration-test/company.integration.test.ts.disabled
  src/integration-test/order.integration.test.ts.disabled
  src/integration-test/user.integration.test.ts.disabled
Labels: Bug, Test

#188 fix: 통합테스트 integration.test 비활성화 (ci/cd 동작 확인을 위해)
  src/integration-test/budget.integration.test.ts.disabled
  src/integration-test/cart.integration.test.ts.disabled
  src/integration-test/company.integration.test.ts.disabled
  src/integration-test/favorite.integration.test.ts.disabled
  src/integration-test/order.integration.test.ts.disabled
  src/integration-test/product.integration.test.ts.disabled
  src/integration-test/test-utils.ts.disabled
  src/integration-test/user.integration.test.ts.disabled
Labels: Bug, Test

#189 chore: dev->main으로 머지 [이지수B]
  .github/workflows/deploy.yml
  jest.config.js
  package.json
  src/integration-test/budget.integration.test.ts.disabled
  src/integration-test/cart.integration.test.ts.disabled
  src/integration-test/company.integration.test.ts.disabled
  src/integration-test/favorite.integration.test.ts.disabled
  src/integration-test/order.integration.test.ts.disabled
  src/integration-test/product.integration.test.ts.disabled
  src/integration-test/test-utils.ts.disabled
  src/integration-test/user.integration.test.ts.disabled
  test-sequencer.js
Labels: Chore

#196 release: main으로 배포
  .github/workflows/deploy.yml
  README.md
  prisma/mocks/product.mock.ts
  prisma/mocks/receipt.mock.ts
  prisma/seed.ts
  tsconfig.json
Labels: Chore

#198 release: main으로 머지(목데이터 수정)
  prisma/mocks/product.mock.ts
Labels: Chore, Refactor
