Repository De-cal/6-Snack-BE, pull requests merged in 2025-07, with the labels that each got.

#2 chore: env.example 추가
  .env.example
Labels: Chore

#11 chore: 스키마 CartItem에 Unique 제약조건 추가 [이태빈]
  package-lock.json
  package.json
  prisma/migrations/20250709022559_add_unique_constraint/migration.sql
  prisma/migrations/20250709023814_add_hashed_refresh_token_field_in_user_table/migration.sql
  prisma/schema.prisma
Labels: Chore

#12 chore: Order 스키마에 approver 추가 [이태빈]
  prisma/migrations/20250709025210_add_approver_field_in_order_table/migration.sql
  prisma/mocks/order.mock.ts
  prisma/schema.prisma
Labels: Chore

#13 feat:cart 목록 조회, 추가, 삭제 구현[조성빈]
  .env.example
  http/cart.http
  src/controllers/cart.controller.ts
  src/dtos/cart.dto.ts
  src/repositories/cart.repository.ts
  src/routes/cart.route.ts
  src/services/cart.service.ts
Labels: Feature, Route, Chore, Refactor

#21 feat: 최고 관리자 예산 수정 API 완성 [이태빈]
  http/auth.http
  http/budget.http
  src/controllers/budget.controller.ts
  src/dtos/budget.dto.ts
  src/middlewares/validatedBudgetBody.middleware.ts
  src/repositories/budget.repository.ts
  src/routes/superAdmin.route.ts
  src/routes/superAdminBudget.route.ts
  src/services/budget.service.ts
  src/types/budget.type.ts
  src/utils/parseNumberOrThrow.ts
Labels: Feature, Route

#23 feat: 상품 Api 기능 완성 [김우주]
  http/auth.http
  http/product.http
  package-lock.json
  package.json
  src/controllers/product.controller.ts
  src/dtos/product.dto.ts
  src/middlewares/upload.middleware.ts
  src/repositories/product.repository.ts
  src/routes/my.route.ts
  src/routes/product.route.ts
  src/services/product.service.ts
  src/utils/s3.ts
Labels: Feature, Route, Refactor

#24 feat/구매 요청 내역(PENDING) 조회, 상세 조회 API 개발 완성 [이태빈]
  http/order.http
  src/controllers/order.controller.ts
  src/dtos/order.dto.ts
  src/middlewares/validateGetOrderQuery.middleware.ts
  src/middlewares/validateUpdateStatusOrderBody.middleware.ts
  src/repositories/order.repository.ts
  src/routes/adminOrder.route.ts
  src/services/order.service.ts
  src/types/order.types.ts
Labels: Feature, Route

#26 feat: 최고 관리자 기능 및 일반 유저 비밀번호 변경 API 구현 [이지수B]
  http/auth.http
  http/user.http
  http/user/user.company.http
  http/user/user.delete.http
  http/user/user.password.http
  http/user/user.role.http
  prisma/mocks/user.mock.ts
  src/controllers/company.controller.ts
  src/controllers/user.controller.ts
  src/dtos/company.dto.ts
  src/dtos/user.dto.ts
  src/repositories/company.repository.ts
  src/repositories/user.repository.ts
  src/routes/superAdmin.route.ts
  src/routes/user.route.ts
  src/services/company.service.ts
  src/services/user.service.ts
  src/types/user.types.ts
Labels: Feature

#35 fix: utils 함수 임포트 오류 수정 [이태빈]
  src/services/order.service.ts
Labels: Bug

#34 feat: 인증 API 관련 코드 개선 & 앱 실행오류 해결 [김홍섭]
  src/controllers/auth.controller.ts
  src/middlewares/jwtAuth.middleware.ts
  src/repositories/auth.repository.ts
  src/routes/auth.route.ts
  src/routes/invite.route.ts
  src/services/auth.service.ts
  src/types/authenticatedRequest.type.ts
  src/types/express.d.ts
  src/utils/date.utils.ts
Labels: Refactor

#41 feat: 상품 리스트 갯수 추가 및 카테고리 추가, 관리자 권한 상품 수정 및 삭제 추가 [김우주]
  http/auth.http
  http/product.http
  src/controllers/product.controller.ts
  src/middlewares/jwtAuth.middleware.ts
  src/repositories/product.repository.ts
  src/routes/admin.route.ts
  src/routes/index.route.ts
  src/types/product.types.ts
Labels: Feature, Refactor

#38 Feat/구매요청API 구현 최종확인(즉시 구매 포함) 및 리팩토링 [장원빈]
  Convention.md
  http/order.http
  http/orderRequest.http
  package-lock.json
  package.json
  src/controllers/order.controller.ts
  src/controllers/orderRequest.controller.ts
  src/dtos/orderRequest.dto.ts
  src/middlewares/errorHandler.middleware.ts
  src/repositories/order.repository.ts
  src/repositories/orderRequest.repository.ts
  src/routes/adminOrder.route.ts
  src/routes/index.route.ts
  src/routes/order.route.ts
  src/routes/orderRequest.route.ts
  src/services/order.service.ts
  src/services/orderRequest.service.ts
  src/types/orderRequest.types.ts
Labels: Refactor

#42 feat: category Api 추가 [김우주]
  http/product.http
  src/controllers/product.controller.ts
  src/repositories/product.repository.ts
  src/routes/product.route.ts
  src/services/product.service.ts
  src/types/product.types.ts
Labels: Feature

#46 feat: aws alb 세팅
  http/auth.http
  http/aws.http
  src/app.ts
  src/routes/index.route.ts
Labels: Route

#49 feat: 내 정보 조회 API 추가 및 장바구니 개수 조회 기능 구현; cors 등록(https); [김홍섭]
  http/auth.http
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/repositories/user.repository.ts
  src/routes/auth.route.ts
  src/routes/user.route.ts
  src/services/user.service.ts
Labels: Feature

#50 chore: 패키지 취약점 보완(multer 업데이트) [이태빈]
  http/order.http
  package-lock.json
Labels: Bug

#52 fix: 유저 목록조회 쿼리 숫자로 형변환되게 설정 [이지수B]
  src/services/user.service.ts
Labels: Bug

#53 chore: mock 데이터 업데이트 [이지수B]
  prisma/mocks/user.mock.ts
Labels: Chore, Refactor

#54 fix:상품상세 페이지에서 상품의 대분류를 조회하기위해 findProductById함수를 변경하였습니다 [조성빈]
  src/repositories/product.repository.ts
Labels: Bug

#55 feat: products 목데이터 추가 생성, getProducts 컨트롤러 함수 수정 [이지수B]
  prisma/mocks/product.mock.ts
  src/controllers/product.controller.ts
Labels: Refactor

#61 feat: 페이지네이션 기능 관련 수정 [이지수B]
  src/controllers/product.controller.ts
Labels: Bug

#65 refactor: cart 조회 시 쿼리 이름 수정 [이태빈]
  http/cart.http
  src/controllers/cart.controller.ts
  src/repositories/cart.repository.ts
  src/services/cart.service.ts
Labels: Feature, Refactor

#69 chore: product mock 업데이트 (과자 부분만 s3 연동된 이미지 링크 업데이트) [이지수B]
  prisma/mocks/product.mock.ts
  prisma/seed.ts
Labels: Chore

#70 refactor: 장바구니 조회 응답 수정 [이태빈]
  src/controllers/cart.controller.ts
Labels: Route, Refactor

#72 refactor: 초대 엔드포인트에 인증 추가 [이태빈]
  src/routes/invite.route.ts
Labels: Refactor

#73 chore: 스키마 수정 [이태빈]
  prisma/migrations/20250728042151_add_order_company_id_product_cumulative_sales/migration.sql
  prisma/schema.prisma
Labels: Chore

#75 chore: 스키마 수정 및 타입 오류 해결 [이태빈]
  prisma/migrations/20250728050056_init_cumulative_sales_default/migration.sql
  prisma/schema.prisma
  src/controllers/order.controller.ts
  src/repositories/order.repository.ts
  src/services/order.service.ts
  src/types/product.types.ts
Labels: Chore

#76 product 목데이터 수정 [이태빈]
  prisma/mocks/product.mock.ts
Labels: Chore, Refactor

#77 fix: mock data url 호스트네임 수정 [이지수B]
  prisma/mocks/product.mock.ts
Labels: Bug, Chore

#80 fix: cartItem 목데이터 수정 [이태빈]
  prisma/mocks/cart-item.mock.ts
Labels: Feature, Refactor

#85 chore: 스키마 수정 [이태빈]
  prisma/migrations/20250729025901_remove_ordered_item_table_add_order_id_and_product_id_in_receipt/migration.sql
  prisma/schema.prisma
Labels: Chore

#88 refactor: 목데이터 id 하드코딩 된것 제거 [이지수B]
  prisma/mocks/cart-item.mock.ts
  prisma/mocks/category.mock.ts
  prisma/mocks/company.mock.ts
  prisma/mocks/invite.mock.ts
  prisma/mocks/like.mock.ts
  prisma/mocks/monthly-budget.mock.ts
  prisma/mocks/order.mock.ts
  prisma/mocks/product.mock.ts
  prisma/mocks/receipt.mock.ts
  prisma/mocks/user.mock.ts
  prisma/seed.ts
Labels: Chore

#91 feat: 좋아요 기능 추가 [이태빈]
  http/favorite.http
  prisma/migrations/20250731011640_add_unique_constrant_in_like_table/migration.sql
  prisma/schema.prisma
  src/controllers/favorite.controller.ts
  src/repositories/favorite.repository.ts
  src/routes/favorite.route.ts
  src/routes/index.route.ts
  src/services/favorite.service.ts
  src/types/favorite.types.ts
Labels: Feature, Route
